apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: planification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nourhene112/planification-service1:latest
          ports:
            - containerPort: 11000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: planification
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 11000
      targetPort: 11000
  type: LoadBalancer
